### ISSUE TITLE
Make a google colab noteboook for this bruh

### ISSUE THREAD

**Issue by aertist** [TomBayne/Simple-Face-Image-Motion-Model#1]

**Comment by TomBayne** [comment]
The purpose of this project was to adapt the original Google Colab notebook into a near 'one-click' script, which does not rely on external services such as Google Cloud. This also has the benefit of allowing users to utilise high-end hardware that they may have installed.

If you insist on running this in Google Cloud Collab Notebooks, it should be as simple as copy pasting the script into a notebook and adapting it slightly for notebooks - however at that point you are essentially just reversing what I did here, so you may as well use the original notebook [here](https://colab.research.google.com/github/AliaksandrSiarohin/first-order-model/blob/master/demo.ipynb)

You may find it easier and more effective if you run it on your own hardware though.
